apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: paradispatcher-server
  name: paradispatcher-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: paradispatcher-server
  template:
    metadata:
      labels:
        run: paradispatcher-server
    spec:
      containers:
      - name: paradispatcher-server
        image: docker.io/jonathansavas/parabond-paradispatcher:1.0.0-SNAPSHOT
        env:
          - name: MONGO_SVC_HOST
            value: mongo-0.mongo
          - name: PARAWORKER_SVC_HOST
            value: paraworker-server
          - name: PARAWORKER_SVC_PORT
            value: "9999"
        ports:
        - name: grpc
          containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: paradispatcher-server
  name: paradispatcher-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    port: 9898
    targetPort: 9898
  selector:
    run: paradispatcher-server