apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: paradispatcher-server
  name: paradispatcher-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: paradispatcher-server
  template:
    metadata:
      labels:
        run: paradispatcher-server
    spec:
      containers:
      - name: paradispatcher-server
        image: jonathansavas/parabond-paradispatcher:1.0.0-SNAPSHOT
        resources:
          limits:
            cpu: "2"
#          requests:
#            cpu: "3"
#        args:
#          - -cpus
#          - "4"
        imagePullPolicy: Always
        env:
          - name: MONGO_SVC_HOST
            value: mongo-0.mongo
          - name: PARAWORKER_SVC_HOST
            value: paraworker-server
          - name: PARAWORKER_SVC_PORT
            value: "9999"
          - name: RANGE
            value: "100"
        ports:
        - name: grpc
          containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: paradispatcher-server
  name: paradispatcher-server
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9898
    targetPort: 9898
  selector:
    run: paradispatcher-server