apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: flask-server
  name: flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flask-server
  template:
    metadata:
      labels:
        run: flask-server
    spec:
      containers:
        - name: flask-server
          image: jonathansavas/parabond:flask-server-1.0.0-SNAPSHOT-marist-project
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
          env:
            - name: GCLOUD_TARGET
              value: http://IP:8080
          ports:
            - name: http
              containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: flask-server
  labels:
    run: flask-server
spec:
  type: LoadBalancer
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
      name: http
  selector:
    run: flask-server